### PR TITLE
fix #49 for anonymous unions

### LINKED ISSUE #49: [BUG]: anonyous structs and unions are not added to class fields
### Problem description

When using the simple.py anonymous unions are not added to class fields. In my view they sould be added since they are also class embers and contribute to the object size. For each anonimous union a field with no name should be added to class fields.

### Operating System

Windows

### Installed Python Packages

_No response_

### Reproducible example code

```text
// when parsing this only member and member2 are added to example_class fields.
class example_class {
    int member;
    union {
        std::uint32_t a;
        std::uint16_t b[2];
    };
    int member2;
};
```

### PR DESCRIPTION
**Pull request by tomazsustar**
Trying to fix for unions. Let me know if I'm going in right direction. Then I can add a fix for structs as well.

### CODE REVIEW

**Comment by tomazsustar** [comment]
It seems that there is something wrong with the configuration for the checks:

**Comment by virtuald** [comment]
If you merge in main the checks should run correctly now.

**Comment by virtuald** [comment]
This approach seems fine to me.

**Comment by tomazsustar** [comment]
I finaly found some time and added support for unnamed anonymous structs as well.

**Comment by virtuald** [comment]
Thanks!

**Pull request merged**
